rl_training:
  rl_env:
    # MuJoCo simulation settings
    xml_file: "assets/simulation/tentacle.xml"
    simulation_length_seconds: 4.0
    time_between_steps_seconds: 0.04

    # Actuator/tendon settings
    initial_actuator_position: [0.147, 0.25]

    # Reward shaping
    reward_distance_scale: 100.0
    action_change_penalty_scale: 0.25
    control_penalty_scale: 0.1
  
    # Environment objects
    tip_site_name: "tip_center"
    target_bounds_min: [-0.2, -0.2, 0.125]
    target_bounds_max: [0.2, 0.2, 0.1255]

    # Observation settings
    num_frames: 6
    include_actuator_lengths_in_obs: true

    # Fixed target (optional)
    fixed_target_position: null

  rl_training_params:
    # Environment setup
    num_envs: 20

    # Training duration
    total_timesteps: 5_000_000
    # Evaluation
    eval_freq: 10000
    n_eval_episodes: 10

    # Checkpointing
    save_freq: 50000
    log_dir_base: "results"

    # PPO hyperparameters
    learning_rate: 0.0001
    n_steps: 4096
    batch_size: 256
    n_epochs: 10
    gamma: 0.99
    gae_lambda: 0.95
    clip_range: 0.2
    ent_coef: 0.005
    target_kl: 0.08
    # Network architecture
    net_arch: "256-128"
    activation_fn: "Tanh"

  rl_evaluation:
    num_episodes: 1
    render_delay: 0.05
    deterministic_actions: True
    render_mode: null 
    grid_size: 20
    space_limit: 0.2